name: Android CI - Build unsigned APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Print Java & Gradle info
        run: |
          java -version
          ./gradlew -v

      - name: Build Release APK (assembleRelease)
        run: ./gradlew assembleRelease --no-daemon

      - name: List build outputs (debug)
        run: ls -la app/build/outputs/apk/release || true

      - name: Upload unsigned APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: spiderxplorer-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk